apiVersion: apps/v1
kind: Deployment
metadata:
  name: django-blog
  namespace: default
  labels:
    app: django-blog
spec:
  replicas: 2
  selector:
    matchLabels:
      app: django-blog
  template:
    metadata:
      labels:
        app: django-blog
    spec:
      containers:
        - name: django-blog
          image: rishikesh1207/django-blog:latest
          imagePullPolicy: Always
          ports:
            - containerPort: 8000
          envFrom:
            - secretRef:
                name: django-blog-secrets
          livenessProbe:
            httpGet:
              path: /health/
              port: 8000
            initialDelaySeconds: 30
            periodSeconds: 10
          readinessProbe:
            httpGet:
              path: /readiness/
              port: 8000
            initialDelaySeconds: 15
            periodSeconds: 5
          resources:
            requests:
              cpu: "250m"
              memory: "256Mi"
            limits:
              cpu: "500m"
              memory: "512Mi"
---
apiVersion: v1
kind: Secret
metadata:
  name: django-blog-secrets
  namespace: default
type: Opaque
stringData:
  SECRET_KEY: "django-super-secret-key-production-2026"
  DEBUG: "False"
  ALLOWED_HOSTS: "13.201.135.175,localhost"
  DB_NAME: "blogdb"
  DB_USER: "bloguser"
  DB_PASSWORD: "blogpass"
  DB_HOST: "postgres-service"
  DB_PORT: "5432"
  CORS_ALLOWED_ORIGINS: "https://gleaming-kangaroo-44a074.netlify.app"
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: postgres
  namespace: default
spec:
  replicas: 1
  selector:
    matchLabels:
      app: postgres
  template:
    metadata:
      labels:
        app: postgres
    spec:
      containers:
        - name: postgres
          image: postgres:15-alpine
          ports:
            - containerPort: 5432
          env:
            - name: POSTGRES_DB
              value: "blogdb"
            - name: POSTGRES_USER
              value: "bloguser"
            - name: POSTGRES_PASSWORD
              value: "blogpass"
          volumeMounts:
            - name: postgres-storage
              mountPath: /var/lib/postgresql/data
      volumes:
        - name: postgres-storage
          persistentVolumeClaim:
            claimName: postgres-pvc
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: postgres-pvc
  namespace: default
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 5Gi
