apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: django-blog-ingress
  namespace: default
  annotations:
    kubernetes.io/ingress.class: "nginx"
    nginx.ingress.kubernetes.io/proxy-body-size: "10m"
    nginx.ingress.kubernetes.io/proxy-connect-timeout: "60"
    nginx.ingress.kubernetes.io/proxy-read-timeout: "60"
spec:
  rules:
    - host: your-aws-domain.com   # Replace with your domain or AWS ELB hostname
      http:
        paths:
          - path: /
            pathType: Prefix
            backend:
              service:
                name: django-blog-service
                port:
                  number: 80