apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: django-blog-ingress
  namespace: default
  annotations:
    nginx.ingress.kubernetes.io/proxy-body-size: "10m"
    traefik.ingress.kubernetes.io/router.tls.certresolver: le
spec:
  ingressClassName: traefik
  tls:
    - hosts:
        - 3.109.216.143.nip.io
  rules:
    - host: 3.109.216.143.nip.io
      http:
        paths:
          - path: /
            pathType: Prefix
            backend:
              service:
                name: django-blog-service
                port:
                  number: 80